name: Execução de exemplo

on:
  workflow_dispatch

jobs:
  RunProject:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar projeto
        uses: actions/checkout@v3

      - name: Configurar Node
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Instalar dependecias
        run: npm install

      - name: Rodar projeto
        run: node index.js